version: "3.9"

services:
  coordinator:
    build: ./coordinator/
    container_name: coordinator
    hostname: net
    environment:
      RUST_BACKTRACE: 1
      PORT_MAPPINGS: "[[8013,8031],[8012,8021],[8023,8032]]"
      CLIENT_PORTS: "[8001, 8002, 8003]"
      PORT_TO_PID_MAPPING: "[[8001,1],[8002,2],[8003,3],[8013,1],[8012,1],[8021,2],[8023,2],[8031,3],[8032,3]]"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    ports:
      - "8012:8012"
      - "8013:8013"
      - "8021:8021"
      - "8023:8023"
      - "8031:8031"
      - "8032:8032"
    stdin_open: true
    tty: true
  
  op1:
    build: ./omnipaxos_server/
    container_name: op1
    hostname: op1
    environment: 
      - RUST_BACKTRACE=1
      - CARGO_UNSTABLE_SPARSE_REGISTRY=true
      - PID=1
      - PEERS=[2,3]
      - PEER_ADDRS=["net:8012","net:8013"]
      - API_ADDR=net:8001
    depends_on:
      - coordinator

  op2:
    build: ./omnipaxos_server/
    container_name: op2
    hostname: op2
    environment: 
      - RUST_BACKTRACE=1
      - CARGO_UNSTABLE_SPARSE_REGISTRY=true
      - PID=2
      - PEERS=[1,3]
      - PEER_ADDRS=["net:8021","net:8023"]
      - API_ADDR=net:8002
    depends_on:
      - coordinator

  op3:
    build: ./omnipaxos_server/
    container_name: op3
    hostname: op3
    environment: 
      - RUST_BACKTRACE=1
      - CARGO_UNSTABLE_SPARSE_REGISTRY=true
      - PID=3
      - PEERS=[1,2]
      - PEER_ADDRS=["net:8031","net:8032"]
      - API_ADDR=net:8003
    depends_on:
      - coordinator

