[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "net", "io-util", "time", "io-std"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
rand = "0.8"

